<Project>
  <Import Project="core.props" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Xunit.OpenCategories.V3" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentAssertions.Json" />
    <PackageReference Include="coverlet.msbuild" />
    <PackageReference Include="AutoFixture.Xunit3" />
    <PackageReference Include="FsCheck.Xunit.v3" />
    <PackageReference Include="FakeItEasy" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>